# Generated by Django 5.1.6 on 2025-05-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_chat_messages_alter_user_birthday_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Note",),
    ]
