# Generated by Django 5.1.6 on 2025-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="lastMessage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="UserFollowing",),
    ]
